plugins { id 'dev.architectury.loom' }
dependencies {
    minecraft libs.minecraft
    mappings loom.officialMojangMappings()
    modImplementation libs.fabric.loader
    modImplementation libs.fabric.api
    modCompileOnly libs.modmenu
    implementation project(':common')
}
loom { mods { breath_fog { sourceSet sourceSets.main; sourceSet project(':common').sourceSets.main } } }
apply from: rootProject.file('gradle/qa.gradle')
processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand(version: project.version) }
}
tasks.named('jar', Jar) {
    from project(':common').sourceSets.main.output
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveFileName = "breath-fog-${project.version}-fabric-dev.jar"
}
tasks.named('sourcesJar', Jar) {
    from project(':common').sourceSets.main.allSource
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveFileName = "breath-fog-${project.version}-fabric-sources.jar"
}

tasks.named("remapJar") { archiveFileName = "breath-fog-${project.version}-fabric.jar" }
tasks.named("remapSourcesJar") { archiveFileName = "breath-fog-${project.version}-fabric-sources.jar" }
