plugins { id 'dev.architectury.loom' }
base { archivesName = rootProject.archives_base_name }
sourceSets.main {
    java.srcDir rootProject.file('common/src/main/java')
    resources.srcDir rootProject.file('common/src/main/resources')
}
configurations.forgeRuntimeLibrary {
    exclude group: 'dev.architectury', module: 'architectury-naming-service'
    exclude group: 'dev.architectury', module: 'architectury-mixin-remapper-service'
}
dependencies {
    minecraft libs.minecraft
    mappings loom.officialMojangMappings()
    forge libs.forge
}
loom { mods { breath_fog { sourceSet sourceSets.main } } }
processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') { expand version: project.version }
}
tasks.named('jar', Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveFileName = "breath-fog-${project.version}-forge-dev.jar"

}
tasks.named('sourcesJar', Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveFileName = "breath-fog-${project.version}-forge-sources.jar"
}

apply from: rootProject.file('gradle/qa.gradle')

tasks.named("remapJar") { archiveFileName = "breath-fog-${project.version}-forge.jar" }
tasks.named("remapSourcesJar") { archiveFileName = "breath-fog-${project.version}-forge-sources.jar" }
